#! /bin/sh
set -e
for f in include/regexp9.h src/cmd/ed.c hellowin.c ; do
	test -e "$f" || { echo >&2 "wrong dir($f)"; exit 100; }
done
test -x compile || {
for cc in compile.* ; do
    ./$cc hellowin.c || continue
    cp $cc compile
    break
done
}
./compile hellowin.c	# make sure it works
./libs
./c2o ./compile src/cmd/ed.c -Iinclude
./compile -o ed src/cmd/ed.o src/lib*/*.a src/lib*/*.a
