#! /bin/sh
# Compile $dir/file.c into $dir/file.o (rather than file.o)
case x"$1" in
	(*.c)
		echo >&2 "Usage: $0 gcc file.c # options etc"
		exit 100
		;;
esac
cc="$1" ; shift
case x"$1" in
	(*.c)
		;;
	(*)
		echo >&2 "Not a C file: $1"
		exit 100
		;;
esac
c="$1"; shift
exec "$cc" -c -o "${c%.c}.o" "$c" "$@"
